#!/bin/bash
# Script 1: System Identity Report
# Author: Nandini Nirmal | Course: Open Source Software

# Variables
STUDENT_NAME="Nandni Nirmal"
SOFTWARE_CHOICE="Python"

# System Info
KERNEL=$(uname -r)
USER_NAME=$(whoami)
HOME_DIR=$HOME
UPTIME=$(uptime -p)
DATE=$(date)

# Distro
DISTRO=$(cat /etc/os-release | grep PRETTY_NAME | cut -d '"' -f2)

# Display
echo "===================================="
echo " Open Source Audit — $STUDENT_NAME"
echo "===================================="
echo "Software : $SOFTWARE_CHOICE"
echo "Distro   : $DISTRO"
echo "Kernel   : $KERNEL"
echo "User     : $USER_NAME"
echo "Home Dir : $HOME_DIR"
echo "Uptime   : $UPTIME"
echo "Date     : $DATE"
echo "License  : GNU General Public License (GPL)"
